name: 自动部署至腾讯云托管
# on: [push] # push 代码时触发
on:
  push:
    branches:
      - cloudbase

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tencent Cloudbase Github Action Example
    steps:
      - name: Checkout  # 拉取代码
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: build
        run: npm run build && npm run export # 执行部署程序

      - name: Deploy static to Tencent CloudBase # 使用云开发 Github Action 部署
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1
        with:
          secretId: ${{ secrets.QCLOUD_APIKEYID }}
          secretKey: ${{ secrets.QCLOUD_APIKEY }}
          envId: ${{ secrets.QCLOUD_ENV_ID }}
          staticSrcPath: out/